version: '3.8'

services:
  # 1. STORAGE: MinIO (Data Lake)
  minio:
    image: minio/minio:latest
    container_name: football_datalake
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - ./data_lake:/data
    restart: always

  # 2. METADATA DB: Postgres (for Dagster)
  postgres:
    image: postgres:13
    container_name: dagster_db
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 3. ORCHESTRATION: Dagster Webserver (UI)
  dagster_webserver:
    build:
      context: ./ops
      dockerfile: Dockerfile
    container_name: football_orchestrator
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes:
      - ./orchestration:/opt/dagster/app/src
      - ./workspace.yaml:/opt/dagster/app/workspace.yaml
    depends_on:
      - postgres
      - minio
    command: [ "dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "workspace.yaml" ]
    restart: always

  # 4. ORCHESTRATION: Dagster Daemon (Scheduler/Sensors)
  dagster_daemon:
    build:
      context: ./ops
      dockerfile: Dockerfile
    container_name: football_scheduler
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes:
      - ./orchestration:/opt/dagster/app/src
      - ./workspace.yaml:/opt/dagster/app/workspace.yaml
    depends_on:
      - postgres
      - minio
    command: [ "dagster-daemon", "run" ]
    restart: always

volumes:
  postgres_data:
